[package]
name = "quake_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
quake_core = { path = "../quake_core" }

miette = "5.10.0"
nu-cmd-lang = "0.86.0"
nu-command = { version = "0.86.0", features = ["which-support"] }
nu-engine = "0.86.0"
nu-parser = "0.86.0"
nu-path = "0.86.0"
nu-protocol = "0.86.0"
serde = "1.0.190"
nu-cli = "0.86.0"
nu-ansi-term = "0.49.0"
glob = "0.3.1"
