[package]
name = "quake_engine"
version = "0.1.0"

license.workspace = true
edition.workspace = true

[dependencies]
quake_core = { path = "../quake_core" }

glob = "0.3.1"
miette = "5.10.0"
nu-ansi-term = "0.49.0"
nu-cli = "0.87.1"
nu-cmd-lang = "0.87.1"
nu-command = { version = "0.87.1", features = ["which-support"] }
nu-engine = "0.87.1"
nu-parser = "0.87.1"
nu-path = "0.87.1"
nu-protocol = "0.87.1"
parking_lot = "0.12.1"
serde = "1.0.193"
