[package]
name = "quake"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["cargo", "wrap_help"] }

quake_core = { path = "../quake_core" }
quake_engine = { path = "../quake_engine" }
