[package]
name = "quake_errors"
version = "0.1.0"

license.workspace = true
edition.workspace = true

[dependencies]
miette = "5.10.0"
nu-protocol.workspace = true
thiserror = "1.0.56"

[lints]
workspace = true
