[package]
name = "quake_errors"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = "5.10.0"
nu-protocol = "0.87.1"
serde = { version = "1.0.193", features = ["derive"], optional = true }
thiserror = "1.0.50"

[features]
serde = ["dep:serde"]
